name: Deploy to Timeweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
        chmod 600 ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}

    - name: Deploy via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Переход в директорию проекта
          cd $DEPLOY_PATH

          # Установка зависимостей системы (если нужно)
          # sudo apt update
          # sudo apt install -y python3-venv

          # Удаление старых файлов (по желанию)
          rm -rf app production.py requirements.txt .env

          # Копирование новых файлов из репозитория
          scp -r cd64186@cd64186.tw1.ru:/public_html/url-shortener-service/* .

          # Проверка наличия requirements.txt
          # if [ ! -f "requirements.txt" ]; then
          #   echo "Файл requirements.txt отсутствует!"
          #   exit 1
          # fi

          # Создание виртуального окружения
          python3 -m venv venv
          source venv/bin/activate

          # Установка зависимостей
          pip install -r requirements.txt

          # Перезапуск Uvicorn
          pkill -f uvicorn || true
          nohup uvicorn app.main:app --host 0.0.0.0 --port 8080 --reload &